# Generated by Django 4.0.3 on 2022-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_system', models.CharField(max_length=10)),
                ('machine_type', models.CharField(max_length=10)),
                ('machine_number', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_cabinet', models.CharField(max_length=10)),
                ('machine_direction', models.CharField(max_length=5)),
                ('machine_mile', models.CharField(max_length=10)),
            ],
        ),
    ]
