# Generated by Django 4.0.3 on 2022-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_equipmentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pubtime', models.DateTimeField()),
                ('enabled', models.BooleanField()),
                ('press', models.IntegerField()),
                ('catego', models.CharField(max_length=10)),
            ],
        ),
    ]
