# Generated by Django 4.0.3 on 2022-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_newsunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('nickname', models.CharField(max_length=20)),
                ('press', models.IntegerField()),
                ('catego', models.CharField(max_length=10)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.DeleteModel(
            name='Newsunit',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
