# Generated by Django 4.0.3 on 2022-04-24 02:09

import calendar
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_news_delete_newsunit_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(verbose_name=calendar.Calendar.monthdayscalendar)),
                ('inspection_group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_names', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Other_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50)),
                ('machine_cabinet', models.CharField(max_length=10)),
                ('machine_direction', models.CharField(max_length=5)),
                ('machine_mile', models.CharField(max_length=10)),
                ('MOS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.machine_name')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manchine_types', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_system', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='EquipmentDB',
        ),
        migrations.AddField(
            model_name='machine_type',
            name='SY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.system'),
        ),
        migrations.AddField(
            model_name='machine_name',
            name='MN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.machine_type'),
        ),
    ]
