# Generated by Django 4.0.3 on 2022-04-24 03:40

import calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_inspection_machine_name_machine_other_setting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='Machine_System',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(verbose_name=calendar.Calendar.monthdayscalendar),
        ),
    ]
