# Generated by Django 4.0.3 on 2022-04-24 04:02

import calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_inspection_inspection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(verbose_name=calendar.Calendar.monthdayscalendar),
        ),
    ]
