# Generated by Django 4.0.3 on 2022-04-24 04:16

import calendar
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_alter_inspection_inspection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(verbose_name=calendar.Calendar.monthdayscalendar),
        ),
        migrations.AlterField(
            model_name='machine_other_setting',
            name='MOS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.machine_type'),
        ),
        migrations.DeleteModel(
            name='Machine_Name',
        ),
    ]
