# Generated by Django 4.0.3 on 2022-04-26 19:19

import calendar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_alter_inspection_inspection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(verbose_name=calendar.Calendar.monthdayscalendar),
        ),
    ]
